service: starship-sns

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  starship:
    handler: starship.handler

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
